services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: afmarquinhos/epic-motors-app:1.0.4
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development